---
- name: Test web content
  hosts: localhost
  become: true
  become_method: sudo

  tasks:
    - name: Retrieve web content and write to error log on failure

      block:

        - name: Retrieve web content
          ansible.builtin.uri:
            url: http://vagrant1
            return_content: yes
          register: web_content

      rescue:

        - name: Write to error file
          copy:
            content: "{{ web_content | default('No content available') }}"
            dest: error.log
            force: true

